# Generated by Django 4.0.2 on 2022-02-23 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=13, help_text='Восточное направление считается положительным. Западное - отрицательным.', max_digits=16, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=13, help_text='Северное направление считается положительным. Южное - отрицательным.', max_digits=16, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
    ]
