# Generated by Django 4.0.2 on 2022-02-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user_avatars', verbose_name='Аватар'),
        ),
    ]
