# Generated by Django 4.0.2 on 2022-02-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_profile_lovers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lovers',
            field=models.ManyToManyField(blank=True, null=True, to='clients.Profile', verbose_name='Оценившие'),
        ),
    ]
